version: "3"
services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: gamedb
      DB_USERNAME: user
      DB_PASSWORD: password
      FLASK_APP: /app/main.py
    depends_on:
      - db
    volumes:
      - ./:/app
  db:
    image: postgres:13.7
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gamedb
    ports:
      - 5432:5432