version: "3"
services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/gamedb
    depends_on:
      - db
  db:
    image: postgres:13.7
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gamedb
    ports:
      - "5432:5432"
